### ISSUE TITLE
WSUS Server Terminology

### ISSUE THREAD

**Issue by LinealJoe** [sergiomarotco/Best-practice-for-network-segmentation#6]
WSUS no longer uses the master/slave terminology. Instead use upstream & downstream servers.

https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment

**Comment by sergiomarotco** [comment]
Thanks, I'll try to fix it soon!  If you still have comments or if there is a technology that I have not included in the diagram, I will be glad to new issues

**Comment by sergiomarotco** [comment]
@LinealJoe  [release 2.1](https://github.com/sergiomarotco/Best-practice-for-network-segmentation/releases/tag/2.1)
